<meta charset="utf-8" />
<title>Detail Pemesanan</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />
<meta name="MobileOptimized" content="320">

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="{{asset('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet')}}" type="text/css" />
<link href="{{asset('assets/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/plugins/uniform/css/uniform.default.css')}}" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="{{asset('assets/css/print.css')}}" rel="stylesheet" type="text/css" media="print" />
<link href="{{asset('assets/css/style-conquer.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/style.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/style-responsives.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/plugins.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/pages/invoice.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/css/custom.css')}}" rel="stylesheet" type="text/css" />

<!-- END THEME STYLES -->
<link rel="{{asset('shortcut icon" href="favicon.ico')}}" />

<div class="page-content-wrapper">
    <div class="page-content">

        <h1 style="text-align:center">
            Detail Pemesanan <small></small>
        </h1>

        <div class="page-bar">
            <button type="button" class="btn btn-fit-height default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true"></button>
        </div>

        <div class="invoice">

            <div class="row invoice-logo">
                <div class="col-xs-6 invoice-logo-space">
                    <img src="assets/img/primaphoto2.png" alt="" />
                </div>
                <div class="col-xs-6">
                    <p>
                        #5652256 / 28 Feb 2013 <span class="muted">
							Consectetuer adipiscing elit </span>
                    </p>
                </div>
            </div>

            <hr/>
            <div class="row">
                <div class="col-xs-4">
                    <h4>Client:</h4>
                    <ul class="list-unstyled">
                        <li>
                            John Doe
                        </li>
                        <li>
                            Mr Nilson Otto
                        </li>
                        <li>
                            FoodMaster Ltd
                        </li>
                        <li>
                            Madrid
                        </li>
                        <li>
                            Spain
                        </li>
                        <li>
                            1982 OOP
                        </li>
                    </ul>
                </div>
                <div class="col-xs-4">
                    <h4>About:</h4>
                    <ul class="list-unstyled">
                        <li>
                            Drem psum dolor sit amet
                        </li>
                        <li>
                            Laoreet dolore magna
                        </li>
                        <li>
                            Consectetuer adipiscing elit
                        </li>
                        <li>
                            Magna aliquam tincidunt erat volutpat
                        </li>
                        <li>
                            Olor sit amet adipiscing eli
                        </li>
                        <li>
                            Laoreet dolore magna
                        </li>
                    </ul>
                </div>
                <div class="col-xs-4 invoice-payment">
                    <h4>Payment Details:</h4>
                    <ul class="list-unstyled">
                        <li>
                            <strong>V.A.T Reg #:</strong> 542554(DEMO)78
                        </li>
                        <li>
                            <strong>Account Name:</strong> FoodMaster Ltd
                        </li>
                        <li>
                            <strong>SWIFT code:</strong> 45454DEMO545DEMO
                        </li>
                        <li>
                            <strong>V.A.T Reg #:</strong> 542554(DEMO)78
                        </li>
                        <li>
                            <strong>Account Name:</strong> FoodMaster Ltd
                        </li>
                        <li>
                            <strong>SWIFT code:</strong> 45454DEMO545DEMO
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Item
                                </th>
                                <th class="hidden-480">
                                    Description
                                </th>
                                <th class="hidden-480">
                                    Quantity
                                </th>
                                <th class="hidden-480">
                                    Unit Cost
                                </th>
                                <th>
                                    Total
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    1
                                </td>
                                <td>
                                    Hardware
                                </td>
                                <td class="hidden-480">
                                    Server hardware purchase
                                </td>
                                <td class="hidden-480">
                                    32
                                </td>
                                <td class="hidden-480">
                                    $75
                                </td>
                                <td>
                                    $2152
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    2
                                </td>
                                <td>
                                    Furniture
                                </td>
                                <td class="hidden-480">
                                    Office furniture purchase
                                </td>
                                <td class="hidden-480">
                                    15
                                </td>
                                <td class="hidden-480">
                                    $169
                                </td>
                                <td>
                                    $4169
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3
                                </td>
                                <td>
                                    Foods
                                </td>
                                <td class="hidden-480">
                                    Company Anual Dinner Catering
                                </td>
                                <td class="hidden-480">
                                    69
                                </td>
                                <td class="hidden-480">
                                    $49
                                </td>
                                <td>
                                    $1260
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    3
                                </td>
                                <td>
                                    Software
                                </td>
                                <td class="hidden-480">
                                    Payment for Jan 2013
                                </td>
                                <td class="hidden-480">
                                    149
                                </td>
                                <td class="hidden-480">
                                    $12
                                </td>
                                <td>
                                    $866
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <div class="well">
                        <address>
							<strong>Loop, Inc.</strong><br/>
							795 Park Ave, Suite 120<br/>
							San Francisco, CA 94107<br/>
							<abbr title="Phone">P:</abbr> (234) 145-1810 </address>
                        <address>
							<strong>Full Name</strong><br/>
							<a href="mailto:#">first.last@email.com</a>
							</address>
                    </div>
                </div>
                <div class="col-xs-8 invoice-block">
                    <ul class="list-unstyled amounts">
                        <li>
                            <strong>Sub - Total amount:</strong> $9265
                        </li>
                        <li>
                            <strong>Discount:</strong> 12.9%
                        </li>
                        <li>
                            <strong>VAT:</strong> -----
                        </li>
                        <li>
                            <strong>Grand Total:</strong> $12489
                        </li>
                    </ul>
                    <br/>
                    <a class="btn btn-lg btn-info hidden-print" onclick="javascript:window.print();">Print <i class="fa fa-print"></i></a>
                    <a class="btn btn-lg btn-success hidden-print">Submit Your Invoice <i class="fa fa-check"></i></a>
                </div>
            </div>
        </div>

    </div>
</div>




<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<script src="{{asset('assets/plugins/jquery-1.11.0.min.js" type="text/javascript')}}"></script>
<script src="{{asset('assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript')}}"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{{asset('assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript')}}"></script>
<script src="{{asset('assets/plugins/jquery.blockui.min.js" type="text/javascript')}}"></script>
<script src="{{asset('assets/plugins/uniform/jquery.uniform.min.js')}}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="{{asset('assets/scripts/app.js')}}"></script>

<script>
    jQuery(document).ready(function() {
        App.init();
    });
</script>